base_url = "https://alterxyz.github.io/gitblog/"
generate_feeds = true
feed_filenames = ["rss.xml"]
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
[extra]
even_title = "alterxyz's Blog"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags/llm/", name = "LLM"},
    {url = "$BASE_URL/tags/promptengineering/", name = "Prompt Engineering"},
]
